### PR TITLE
Implemented "Empty sea map" key item

### PR DESCRIPTION
**Pull request by FantaX1911**
Implemented "Empty sea map" key item to the monogame branch.

### CODE REVIEW

**Comment by Yukitty** [comment]
Shouldn't you have all the "Empty sea map" commits in the same patch / merge request...?

**Comment by FantaX1911** [comment]
I created the file and edit the other one using the browser, not sure if it is possible to do so.

**Review by jianmingyong — CHANGES_REQUESTED** [review]
Technically that is correct but since "2.5DHero.vbproj" isn't updated with this new file, I won't merge just yet.

I will fix that later xD

**Comment by nilllzz** [comment]
Yeah, please remove this branch and copy the changes over to the other branch. By committing to the other branch, you automatically add the commits to the pull request.

**Pull request closed without merging**
